using Sts2Ai.CombatSimulator;
using Sts2Ai.CombatSimulator.Effects;
using Sts2Ai.CombatSimulator.Powers;
using Sts2Ai.CombatSimulator.State;

namespace Sts2Ai.Cards.Event;

public static class EventCards
{
    public static SimCard Apotheosis() => new() { Id = "APOTHEOSIS", Name = "Apotheosis", Cost = 2, UpgradedCost = 1, Type = CardType.Skill, Rarity = CardRarity.Ancient, DefaultTargetType = TargetType.Self, Keywords = new HashSet<string> { "Exhaust", "Innate" }, Effects = new List<IEffect> { new ApotheosisEffect() }, UpgradedEffects = new List<IEffect> { new ApotheosisEffect() } };
    public static SimCard Apparition() => new() { Id = "APPARITION", Name = "Apparition", Cost = 1, Type = CardType.Skill, Rarity = CardRarity.Ancient, DefaultTargetType = TargetType.Self, Keywords = new HashSet<string> { "Ethereal", "Exhaust" }, Effects = new List<IEffect> { new ApplyPower { PowerFactory = () => new IntangiblePower(), Amount = 1, TargetType = TargetType.Self } }, UpgradedEffects = new List<IEffect> { new ApplyPower { PowerFactory = () => new IntangiblePower(), Amount = 1, TargetType = TargetType.Self } }, UpgradedKeywordsOverrides = true };
    public static SimCard BrightestFlame() => new() { Id = "BRIGHTEST_FLAME", Name = "Brightest Flame", Cost = 0, Type = CardType.Skill, Rarity = CardRarity.Ancient, DefaultTargetType = TargetType.Self, Effects = new List<IEffect> { new GainEnergy { Amount = 2 }, new DrawCards { Amount = 2 }, new LoseMaxHpEffect { Amount = 1 } }, UpgradedEffects = new List<IEffect> { new GainEnergy { Amount = 3 }, new DrawCards { Amount = 3 }, new LoseMaxHpEffect { Amount = 1 } } };
    public static SimCard ByrdSwoop() => new() { Id = "BYRD_SWOOP", Name = "Byrd Swoop", Cost = 0, Type = CardType.Attack, Rarity = CardRarity.Event, DefaultTargetType = TargetType.SingleEnemy, Effects = new List<IEffect> { new DealDamage { BaseAmount = 14, Props = ValueProp.Move } }, UpgradedEffects = new List<IEffect> { new DealDamage { BaseAmount = 18, Props = ValueProp.Move } } };
    public static SimCard Caltrops() => new() { Id = "CALTROPS", Name = "Caltrops", Cost = 1, Type = CardType.Power, Rarity = CardRarity.Event, DefaultTargetType = TargetType.Self, Effects = new List<IEffect> { new ApplyPower { PowerFactory = () => new ThornsPower(), Amount = 3, TargetType = TargetType.Self } }, UpgradedEffects = new List<IEffect> { new ApplyPower { PowerFactory = () => new ThornsPower(), Amount = 5, TargetType = TargetType.Self } } };
    public static SimCard Clash() => new() { Id = "CLASH", Name = "Clash", Cost = 0, Type = CardType.Attack, Rarity = CardRarity.Event, DefaultTargetType = TargetType.SingleEnemy, Effects = new List<IEffect> { new DealDamage { BaseAmount = 14, Props = ValueProp.Move } }, UpgradedEffects = new List<IEffect> { new DealDamage { BaseAmount = 18, Props = ValueProp.Move } } };
    public static SimCard Distraction() => new() { Id = "DISTRACTION", Name = "Distraction", Cost = 1, UpgradedCost = 0, Type = CardType.Skill, Rarity = CardRarity.Event, DefaultTargetType = TargetType.Self, Keywords = new HashSet<string> { "Exhaust" }, Effects = new List<IEffect> { new GenerateRandomSkillInHand() }, UpgradedEffects = new List<IEffect> { new GenerateRandomSkillInHand() } };
    public static SimCard DualWield() => new() { Id = "DUAL_WIELD", Name = "Dual Wield", Cost = 1, Type = CardType.Skill, Rarity = CardRarity.Event, DefaultTargetType = TargetType.Self, Effects = new List<IEffect> { new DualWieldEffect { CopyCount = 1 } }, UpgradedEffects = new List<IEffect> { new DualWieldEffect { CopyCount = 2 } } };
    public static SimCard Enlightenment() => new() { Id = "ENLIGHTENMENT", Name = "Enlightenment", Cost = 0, Type = CardType.Skill, Rarity = CardRarity.Event, DefaultTargetType = TargetType.Self, Keywords = new HashSet<string> { "Exhaust" }, Effects = new List<IEffect> { new EnlightenmentEffect() }, UpgradedEffects = new List<IEffect> { new EnlightenmentUpgradedEffect() } };
    public static SimCard Entrench() => new() { Id = "ENTRENCH", Name = "Entrench", Cost = 2, UpgradedCost = 1, Type = CardType.Skill, Rarity = CardRarity.Event, DefaultTargetType = TargetType.Self, Effects = new List<IEffect> { new EntrenchEffect() }, UpgradedEffects = new List<IEffect> { new EntrenchEffect() } };
    public static SimCard Exterminate() => new() { Id = "EXTERMINATE", Name = "Exterminate", Cost = 1, Type = CardType.Attack, Rarity = CardRarity.Event, DefaultTargetType = TargetType.AllEnemies, Effects = new List<IEffect> { new DealDamage { BaseAmount = 3, Props = ValueProp.Move, HitCount = 4 } }, UpgradedEffects = new List<IEffect> { new DealDamage { BaseAmount = 4, Props = ValueProp.Move, HitCount = 4 } } };
    public static SimCard FeedingFrenzy() => new() { Id = "FEEDING_FRENZY", Name = "Feeding Frenzy", Cost = 0, Type = CardType.Skill, Rarity = CardRarity.Event, DefaultTargetType = TargetType.Self, Effects = new List<IEffect> { new ApplyPower { PowerFactory = () => new StrengthPower(), Amount = 5, TargetType = TargetType.Self } }, UpgradedEffects = new List<IEffect> { new ApplyPower { PowerFactory = () => new StrengthPower(), Amount = 7, TargetType = TargetType.Self } } };
    public static SimCard HelloWorld() => new() { Id = "HELLO_WORLD", Name = "Hello World", Cost = 1, Type = CardType.Power, Rarity = CardRarity.Event, DefaultTargetType = TargetType.Self, Effects = new List<IEffect> { new ApplyPower { PowerFactory = () => new PlaceholderPower(), Amount = 1, TargetType = TargetType.Self } }, UpgradedEffects = new List<IEffect> { new ApplyPower { PowerFactory = () => new PlaceholderPower(), Amount = 1, TargetType = TargetType.Self } }, UpgradedKeywords = new HashSet<string> { "Innate" }, UpgradedKeywordsOverrides = true };
    public static SimCard MadScience() => new() { Id = "MAD_SCIENCE", Name = "Mad Science", Cost = 1, Type = CardType.Attack, Rarity = CardRarity.Event, DefaultTargetType = TargetType.SingleEnemy, Effects = new List<IEffect> { new DealDamage { BaseAmount = 12, Props = ValueProp.Move } }, UpgradedEffects = new List<IEffect> { new DealDamage { BaseAmount = 12, Props = ValueProp.Move } }, UpgradedKeywords = new HashSet<string> { "Innate" }, UpgradedKeywordsOverrides = true };
    public static SimCard Maul() => new() { Id = "MAUL", Name = "Maul", Cost = 1, Type = CardType.Attack, Rarity = CardRarity.Ancient, DefaultTargetType = TargetType.SingleEnemy, Effects = new List<IEffect> { new DealDamage { BaseAmount = 5, Props = ValueProp.Move, HitCount = 2 } }, UpgradedEffects = new List<IEffect> { new DealDamage { BaseAmount = 6, Props = ValueProp.Move, HitCount = 2 } } };
    public static SimCard Metamorphosis() => new() { Id = "METAMORPHOSIS", Name = "Metamorphosis", Cost = 2, Type = CardType.Skill, Rarity = CardRarity.Event, DefaultTargetType = TargetType.Self, Keywords = new HashSet<string> { "Exhaust" }, Effects = new List<IEffect> { new MetamorphosisEffect { CardCount = 3 } }, UpgradedEffects = new List<IEffect> { new MetamorphosisEffect { CardCount = 5 } } };
    public static SimCard NeowsFury() => new() { Id = "NEOWS_FURY", Name = "Neow's Fury", Cost = 1, Type = CardType.Attack, Rarity = CardRarity.Ancient, DefaultTargetType = TargetType.SingleEnemy, Keywords = new HashSet<string> { "Exhaust" }, Effects = new List<IEffect> { new DealDamage { BaseAmount = 10, Props = ValueProp.Move }, new NeowsFuryEffect { CardCount = 2 } }, UpgradedEffects = new List<IEffect> { new DealDamage { BaseAmount = 14, Props = ValueProp.Move }, new NeowsFuryEffect { CardCount = 3 } } };
    public static SimCard Outmaneuver() => new() { Id = "OUTMANEUVER", Name = "Outmaneuver", Cost = 1, Type = CardType.Skill, Rarity = CardRarity.Event, DefaultTargetType = TargetType.Self, Effects = new List<IEffect> { new ApplyPower { PowerFactory = () => new PlaceholderPower(), Amount = 2, TargetType = TargetType.Self } }, UpgradedEffects = new List<IEffect> { new ApplyPower { PowerFactory = () => new PlaceholderPower(), Amount = 3, TargetType = TargetType.Self } } };
    public static SimCard Peck() => new() { Id = "PECK", Name = "Peck", Cost = 1, Type = CardType.Attack, Rarity = CardRarity.Event, DefaultTargetType = TargetType.SingleEnemy, Effects = new List<IEffect> { new DealDamage { BaseAmount = 2, Props = ValueProp.Move, HitCount = 3 } }, UpgradedEffects = new List<IEffect> { new DealDamage { BaseAmount = 2, Props = ValueProp.Move, HitCount = 4 } } };
    public static SimCard Rebound() => new() { Id = "REBOUND", Name = "Rebound", Cost = 1, Type = CardType.Attack, Rarity = CardRarity.Event, DefaultTargetType = TargetType.SingleEnemy, Effects = new List<IEffect> { new DealDamage { BaseAmount = 9, Props = ValueProp.Move }, new ApplyPower { PowerFactory = () => new PlaceholderPower(), Amount = 1, TargetType = TargetType.Self } }, UpgradedEffects = new List<IEffect> { new DealDamage { BaseAmount = 12, Props = ValueProp.Move }, new ApplyPower { PowerFactory = () => new PlaceholderPower(), Amount = 1, TargetType = TargetType.Self } } };
    public static SimCard Relax() => new() { Id = "RELAX", Name = "Relax", Cost = 3, Type = CardType.Skill, Rarity = CardRarity.Ancient, DefaultTargetType = TargetType.Self, Keywords = new HashSet<string> { "Exhaust" }, Effects = new List<IEffect> { new GainBlock { BaseAmount = 15, Props = ValueProp.Move }, new ApplyPower { PowerFactory = () => new PlaceholderPower(), Amount = 2, TargetType = TargetType.Self }, new ApplyPower { PowerFactory = () => new PlaceholderPower(), Amount = 2, TargetType = TargetType.Self } }, UpgradedEffects = new List<IEffect> { new GainBlock { BaseAmount = 17, Props = ValueProp.Move }, new ApplyPower { PowerFactory = () => new PlaceholderPower(), Amount = 3, TargetType = TargetType.Self }, new ApplyPower { PowerFactory = () => new PlaceholderPower(), Amount = 3, TargetType = TargetType.Self } } };
    public static SimCard RipAndTear() => new() { Id = "RIP_AND_TEAR", Name = "Rip and Tear", Cost = 1, Type = CardType.Attack, Rarity = CardRarity.Event, DefaultTargetType = TargetType.RandomEnemy, Effects = new List<IEffect> { new DealDamage { BaseAmount = 7, Props = ValueProp.Move, HitCount = 2, TargetType = TargetType.RandomEnemy } }, UpgradedEffects = new List<IEffect> { new DealDamage { BaseAmount = 9, Props = ValueProp.Move, HitCount = 2, TargetType = TargetType.RandomEnemy } } };
    public static SimCard Squash() => new() { Id = "SQUASH", Name = "Squash", Cost = 1, Type = CardType.Attack, Rarity = CardRarity.Event, DefaultTargetType = TargetType.SingleEnemy, Effects = new List<IEffect> { new DealDamage { BaseAmount = 10, Props = ValueProp.Move }, new ApplyPower { PowerFactory = () => new VulnerablePower(), Amount = 2, TargetType = TargetType.SingleEnemy } }, UpgradedEffects = new List<IEffect> { new DealDamage { BaseAmount = 12, Props = ValueProp.Move }, new ApplyPower { PowerFactory = () => new VulnerablePower(), Amount = 3, TargetType = TargetType.SingleEnemy } } };
    public static SimCard Stack() => new() { Id = "STACK", Name = "Stack", Cost = 1, Type = CardType.Skill, Rarity = CardRarity.Event, DefaultTargetType = TargetType.Self, Effects = new List<IEffect> { new StackEffect() }, UpgradedEffects = new List<IEffect> { new StackUpgradedEffect() } };
    public static SimCard ToricToughness() => new() { Id = "TORIC_TOUGHNESS", Name = "Toric Toughness", Cost = 1, Type = CardType.Power, Rarity = CardRarity.Event, DefaultTargetType = TargetType.Self, Effects = new List<IEffect> { new ApplyPower { PowerFactory = () => new PlatingPower(), Amount = 4, TargetType = TargetType.Self } }, UpgradedEffects = new List<IEffect> { new ApplyPower { PowerFactory = () => new PlatingPower(), Amount = 6, TargetType = TargetType.Self } } };
    public static SimCard Wish() => new() { Id = "WISH", Name = "Wish", Cost = 2, Type = CardType.Skill, Rarity = CardRarity.Ancient, DefaultTargetType = TargetType.Self, Effects = new List<IEffect> { new GainBlock { BaseAmount = 10, Props = ValueProp.Move }, new GainEnergy { Amount = 3 }, new DrawCards { Amount = 3 } }, UpgradedEffects = new List<IEffect> { new GainBlock { BaseAmount = 10, Props = ValueProp.Move }, new GainEnergy { Amount = 3 }, new DrawCards { Amount = 3 } } };
    public static SimCard Whistle() => new() { Id = "WHISTLE", Name = "Whistle", Cost = 0, Type = CardType.Skill, Rarity = CardRarity.Event, DefaultTargetType = TargetType.Self, Keywords = new HashSet<string> { "Exhaust" }, Effects = new List<IEffect> { new DrawCards { Amount = 2 }, new ApplyPower { PowerFactory = () => new VulnerablePower(), Amount = 1, TargetType = TargetType.Self } }, UpgradedEffects = new List<IEffect> { new DrawCards { Amount = 3 }, new ApplyPower { PowerFactory = () => new VulnerablePower(), Amount = 1, TargetType = TargetType.Self } } };
}
