using Sts2Ai.CombatSimulator;
using Sts2Ai.CombatSimulator.Effects;
using Sts2Ai.CombatSimulator.Powers;
using Sts2Ai.CombatSimulator.State;

namespace Sts2Ai.Cards.Token;

public static class TokenCards
{
    public static SimCard Disintegration() => new() { Id = "DISINTEGRATION", Name = "Disintegration", Cost = -1, Type = CardType.Status, Rarity = CardRarity.Status, DefaultTargetType = TargetType.None };
    public static SimCard Fuel() => new() { Id = "FUEL", Name = "Fuel", Cost = 0, Type = CardType.Skill, Rarity = CardRarity.Token, DefaultTargetType = TargetType.Self, Keywords = new HashSet<string> { "Exhaust" }, Effects = new List<IEffect> { new GainEnergy { Amount = 1 }, new DrawCards { Amount = 1 } }, UpgradedEffects = new List<IEffect> { new GainEnergy { Amount = 1 }, new DrawCards { Amount = 2 } } };
    public static SimCard GiantRock() => new() { Id = "GIANT_ROCK", Name = "Giant Rock", Cost = 1, Type = CardType.Attack, Rarity = CardRarity.Token, DefaultTargetType = TargetType.SingleEnemy, Effects = new List<IEffect> { new DealDamage { BaseAmount = 16, Props = ValueProp.Move } }, UpgradedEffects = new List<IEffect> { new DealDamage { BaseAmount = 20, Props = ValueProp.Move } } };
    public static SimCard Luminesce() => new() { Id = "LUMINESCE", Name = "Luminesce", Cost = 0, Type = CardType.Skill, Rarity = CardRarity.Token, DefaultTargetType = TargetType.Self, Keywords = new HashSet<string> { "Exhaust", "Retain" }, Effects = new List<IEffect> { new GainEnergy { Amount = 2 } }, UpgradedEffects = new List<IEffect> { new GainEnergy { Amount = 3 } } };
    public static SimCard MindRot() => new() { Id = "MIND_ROT", Name = "Mind Rot", Cost = -1, Type = CardType.Status, Rarity = CardRarity.Status, DefaultTargetType = TargetType.None };
    public static SimCard MinionDiveBomb() => new() { Id = "MINION_DIVE_BOMB", Name = "Minion Dive Bomb", Cost = 0, Type = CardType.Attack, Rarity = CardRarity.Token, DefaultTargetType = TargetType.SingleEnemy, Tags = new HashSet<string> { "Minion" }, Keywords = new HashSet<string> { "Exhaust" }, Effects = new List<IEffect> { new DealDamage { BaseAmount = 13, Props = ValueProp.Move } }, UpgradedEffects = new List<IEffect> { new DealDamage { BaseAmount = 16, Props = ValueProp.Move } } };
    public static SimCard MinionSacrifice() => new() { Id = "MINION_SACRIFICE", Name = "Minion Sacrifice", Cost = 0, Type = CardType.Skill, Rarity = CardRarity.Token, DefaultTargetType = TargetType.Self, Tags = new HashSet<string> { "Minion" }, Keywords = new HashSet<string> { "Exhaust" }, Effects = new List<IEffect> { new GainBlock { BaseAmount = 8, Props = ValueProp.Move } }, UpgradedEffects = new List<IEffect> { new GainBlock { BaseAmount = 11, Props = ValueProp.Move } } };
    public static SimCard MinionStrike() => new() { Id = "MINION_STRIKE", Name = "Minion Strike", Cost = 0, Type = CardType.Attack, Rarity = CardRarity.Token, DefaultTargetType = TargetType.SingleEnemy, Tags = new HashSet<string> { "Strike", "Minion" }, Keywords = new HashSet<string> { "Exhaust" }, Effects = new List<IEffect> { new DealDamage { BaseAmount = 6, Props = ValueProp.Move }, new DrawCards { Amount = 1 } }, UpgradedEffects = new List<IEffect> { new DealDamage { BaseAmount = 9, Props = ValueProp.Move }, new DrawCards { Amount = 1 } } };
    public static SimCard Shiv() => new() { Id = "SHIV", Name = "Shiv", Cost = 0, Type = CardType.Attack, Rarity = CardRarity.Token, DefaultTargetType = TargetType.SingleEnemy, Tags = new HashSet<string> { "Shiv" }, Keywords = new HashSet<string> { "Exhaust" }, Effects = new List<IEffect> { new DealDamage { BaseAmount = 4, Props = ValueProp.Move } }, UpgradedEffects = new List<IEffect> { new DealDamage { BaseAmount = 6, Props = ValueProp.Move } } };
    public static SimCard Sloth() => new() { Id = "SLOTH", Name = "Sloth", Cost = -1, Type = CardType.Status, Rarity = CardRarity.Status, DefaultTargetType = TargetType.None };
    public static SimCard Soul() => new() { Id = "SOUL", Name = "Soul", Cost = 0, Type = CardType.Skill, Rarity = CardRarity.Token, DefaultTargetType = TargetType.Self, Keywords = new HashSet<string> { "Exhaust" }, Effects = new List<IEffect> { new DrawCards { Amount = 2 } }, UpgradedEffects = new List<IEffect> { new DrawCards { Amount = 3 } } };
    public static SimCard SovereignBlade() => new() { Id = "SOVEREIGN_BLADE", Name = "Sovereign Blade", Cost = 2, UpgradedCost = 1, Type = CardType.Attack, Rarity = CardRarity.Token, DefaultTargetType = TargetType.SingleEnemy, Keywords = new HashSet<string> { "Retain" }, Effects = new List<IEffect> { new DealDamage { BaseAmount = 10, Props = ValueProp.Move } }, UpgradedEffects = new List<IEffect> { new DealDamage { BaseAmount = 10, Props = ValueProp.Move } } };
    public static SimCard SweepingGaze() => new() { Id = "SWEEPING_GAZE", Name = "Sweeping Gaze", Cost = 0, Type = CardType.Attack, Rarity = CardRarity.Token, DefaultTargetType = TargetType.RandomEnemy, Keywords = new HashSet<string> { "Ethereal", "Exhaust" }, Effects = new List<IEffect> { new DealDamage { BaseAmount = 10, Props = ValueProp.Move, TargetType = TargetType.RandomEnemy } }, UpgradedEffects = new List<IEffect> { new DealDamage { BaseAmount = 15, Props = ValueProp.Move, TargetType = TargetType.RandomEnemy } } };
    public static SimCard WasteAway() => new() { Id = "WASTE_AWAY", Name = "Waste Away", Cost = -1, Type = CardType.Status, Rarity = CardRarity.Status, DefaultTargetType = TargetType.None };
}
